### ISSUE TITLE
Extra line padding in source and literal blocks

### ISSUE THREAD

**Issue by dsquare20** [asciidoc/asciidoc-py3#139]
Thanks for porting Asciidoc to Python3.

When creating source or literal blocks , there is a bigger line-height in the version created with Asciidoc 9.0.2 and Python 3. This extra space does not improve readabiilty of source, in my opinion

Please see attached source txt and html for Asciidoc 8.6.9 and 9.0.2
The asciidoc file blocks.txt contains several types of blocks with multiple lines.
[blocks.txt](https://github.com/asciidoc/asciidoc-py3/files/5101059/blocks.txt)

The created html files come up with different layout.
[blocks_a2d.zip](https://github.com/asciidoc/asciidoc-py3/files/5101063/blocks_a2d.zip)

Tried to change the CSS but didn't find the right setting.
Tested on Windows with Firefox 68.9 and basic asciidoc stylesheet 

Thx
DD

**Comment by elextr** [comment]
Hmmm, Asciidoc seems to be outputting double spacing between all content lines, that doesn't matter on normal text blocks, but listing and literal blocks that become `<pre>` entities it matters.

**Comment by elextr** [comment]
Maybe a missing `end=''` on a print somewhere.

**Comment by hoadlck** [comment]
Looks like the input file is in Windows format: it has carriage return/line feed in it.

I see that the uses of [open](https://docs.python.org/3/library/functions.html#open) in AsciiDoc is using universal newlines, but this was a feature that was not available in Python 2.x.  

If you look [here](https://github.com/asciidoc/asciidoc-py3/blob/master/asciidoc.py#L4582), it appears that the `Writer` class assumes what the end of line characters are going to be.  You can see when it [writes a line](https://github.com/asciidoc/asciidoc-py3/blob/master/asciidoc.py#L4609) that it is inserting these characters.  Yet, since universal newlines is enabled...I am not sure what happens.  Seems reasonable that one would get extra returns.

I will try to verify this hypothesis tonight.

**Comment by hoadlck** [comment]
This definitely involves universal newline mode.  If you look at a output file generated on Windows, it has "/r/r/n` as the line ending.

It seems like it would be proper to let the lower level Python code handle the appropriate newlines, but the existing code was more complicated than I could easily grok.  So, I just disabled universal newlines in the output, and let AsciiDoc do its normal operation.

The universal newline mode did not seem to make any difference on the reading of input files, so I left those as is.  This does not seem right to me, but I would want to have a deeper understanding of how all of this works before changing more things.

**Comment by MasterOdin** [comment]
This was fixed as part of the 9.0.3 release.
