### ISSUE TITLE
9.0.4 adding DOS line endings to a few lines

### ISSUE THREAD

**Issue by hobbes1069** [asciidoc/asciidoc-py3#154]
I package fldigi for Fedora linux and when asciidoc was updated to 9.0.4 the build started failing with strange errors. Asciidoc is used to generate an html file from a text file, which is then subsequently processed via sed to produce a c++ file suitable for inclusion.

For some reason 3 lines are getting ^M dos line endings of about a 1000 line file.

```
--- fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html     2020-12-03 08:19:54.596151576 -0600
+++ fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html        2020-12-03 07:40:44.117096417 -0600
@@ -4,7 +4,7 @@
 <html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
 <head>
 <meta http-equiv="Content-Type" content="application/xhtml+xml; charset=UTF-8" />
-<meta name="generator" content="AsciiDoc 9.0.2" />
+<meta name="generator" content="AsciiDoc 9.0.4" />
 <title>Beginners' Guide to Fldigi</title>
 <style type="text/css">
 /* Shared CSS for AsciiDoc xhtml11 and html5 backends */
@@ -735,9 +735,9 @@
 <body class="article">
 <div id="header">
 <h1>Beginners' Guide to Fldigi</h1>
-<div id="toc">
-  <div id="toctitle">Table of Contents</div>
-  <noscript><p><b>JavaScript must be enabled in your browser to display the table of contents.</b></p></noscript>
+<div id="toc">
+  <div id="toctitle">Table of Contents</div>
+  <noscript><p><b>JavaScript must be enabled in your browser to display the table of contents.</b></p></noscript>
 </div>
 </div>
 <div id="content">
```

It doesn't show in the diff unless using a paginator but obviously diff is seeing the lines as different. Fedora 33 has 9.0.2 while Fedora 34 (Rawhide) has 9.0.4.

```
# file fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.txt
fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.txt: UTF-8 Unicode text
# file fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html
fedora-33-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html: XML 1.0 document, UTF-8 Unicode text
# file fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.txt
fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.txt: UTF-8 Unicode text
# file fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html
fedora-rawhide-x86_64/root/builddir/build/BUILD/fldigi-4.1.17/doc/guide.html: XML 1.0 document, UTF-8 Unicode text, with CRLF, LF line terminators
```

For some reason the CRLF terminators are working their way in but they are not present in the guide.txt input file.

**Comment by MasterOdin** [comment]
Could you add the text file you're using here as an attachment to your post?

**Comment by hobbes1069** [comment]
[guide.txt](https://github.com/asciidoc/asciidoc-py3/files/5638734/guide.txt)

**Comment by hoadlck** [comment]
I did some research to try to narrow this down...

As near as I can deduce, the problem was noticed running something similar to the following command:
```
% python3 asciidoc.py --backend=xhtml11 --attribute=toc guide.txt
```

I ran this command with the two releases, and the resulting files are available in the attached [guide_rpi_xhtml11.zip](https://github.com/asciidoc/asciidoc-py3/files/5640658/guide_rpi_xhtml11.zip) file.  Shown below are excerpts from the part of the files that have differences.

File guide_rpi_xhtml11_9.0.2.html
```
<h1>Beginners' Guide to Fldigi</h1>^M
<div id="toc">
  <div id="toctitle">Table of Contents</div>
  <noscript><p><b>JavaScript must be enabled in your browser to display the table of contents.</b></p></noscript>
</div>^M
</div>^M
```

File guide_rpi_xhtml11_9.0.4.html
```
<h1>Beginners' Guide to Fldigi</h1>^M
<div id="toc">^M
  <div id="toctitle">Table of Contents</div>^M
  <noscript><p><b>JavaScript must be enabled in your browser to display the table of contents.</b></p></noscript>^M
</div>^M
</div>^M
```

So, in my attempt to re-create this, the 9.0.4 file has ^M characters on all lines, while the 9.0.2 file is missing ^M characters on those specific 3 lines.

The change available in in 9.0.4 [here](https://github.com/asciidoc/asciidoc-py3/blob/9.0.4/asciidoc.py#L972) is what is causing the difference.  In 9.0.2, the line was like [this](https://github.com/asciidoc/asciidoc-py3/blob/9.0.2/asciidoc.py#L972): only a new line was inserted.  But, 9.0.4 changed this to use a consistent default line ending (i.e. carriage return/line feed).  I restored that line to the way it was originally, and the files matched.

What confuses me is why the parsing of the HTML file worked with 9.0.2 but failed with 9.0.4?  The newer 9.0.4 seems superior, as it has consistent line endings.  If there was something about the ^M characters that the post-processing sed script did not like, then why didn't it choke on the original file?

I am guessing that there was something about the file generated with 9.0.2 having *some* lines with UNIX line endings which is causing the post-processing script to behave differently.  The file generated with 9.0.4 is consistent with Windows line endings, so maybe it is being processed in a different mode?

**Comment by hobbes1069** [comment]
Ok, I'm still learning the internals of the fldigi package so someone just hinted at me that there is also an asccidoc.conf file with this as the contents which may partially explain the inverted behavior in our results:

```
[miscellaneous]
newline=\n
```

**Comment by hoadlck** [comment]
OK.  This makes more sense now.  It looks like the problem is that the code [here](https://github.com/asciidoc/asciidoc-py3/blob/9.0.4/asciidoc.py#L972) is using the default setting instead of the value from the attribute.

I will try to make a fix later on tonight.

**Comment by hobbes1069** [comment]
Thanks!
