### ISSUE TITLE
Building issues (xmllint)

### ISSUE THREAD

**Issue by an9wer** [asciidoc/asciidoc-py3#58]
Hi, I was in the master branch to build the code by using the `make` command, it throwed the following error:
```
a2x: ERROR: "xmllint" --nonet --noout --valid "/path/to/asciidoc-py3/doc/asciidoc.1.xml" returned non-zero exit status 4
```

I also tried to run the xmllint command above from my terminal, and the output is:
```
/path/to/asciidoc-py3/doc/asciidoc.1.xml:5: validity error : Validation failed: no DTD found !
<refentry lang="en">
                   ^
```

But when I removed the `--valid` option in the above command, it ran successfully.

P.S. The output of `xmllint --version` is:
```
xmllint: using libxml version 20904
   compiled with: Threads Tree Output Push Reader Patterns Writer SAXv1 FTP HTTP DTDValid HTML Legacy C14N Catalog XPath XPointer XInclude Iconv ICU ISO8859X Unicode Regexps Automata Expr Schemas Schematron Modules Debug Zlib Lzma
```

**Comment by elextr** [comment]
> `Validation failed: no DTD found !<refentry lang="en">`

I think that means you don't have the right data files installed for xmllint.  You could try running the command without the --nonet so it goes and looks for them on the internet.

**Comment by an9wer** [comment]
@elextr Thanks for your reply. 

I have retried it by removing the "--nonet" option and it works well.

But, to make the build command successful, it seems that I need to modify the source code of `a2x.py` by removing the "--nonet" option. So I want to know is there another way to make that effect. Or is this option required? if not, does it need to remove this option?

**Comment by elextr** [comment]
You can tell a2x not to run xmllint with the -L or --no-xmllint option.  xmllint is a check, its not absolutely needed to convert documents.  Its a check for validity of the output since input documents that work for one output format say HTML may produce incorrect outputs in others, particularly docbook, its not practical to re-implement all the checks in Asciidoc, especially when they are already in xmllint. See also FAQ 7.

The proper solution is to install the data that xmllint uses but how thats done is system specific.

The --nonet is there so that a2x does not access the network by default. It would probably be acceptable if someone made a pull request to add an option to a2x that did not use it and to allowed network access instead if the data is not local.

**Comment by an9wer** [comment]
@elextr Your answer is really what I want. Thanks again :)
