### ISSUE TITLE
Time to change the subtext?

### ISSUE THREAD

**Issue by cclauss** [asciidoc/asciidoc-py3#65]
![A2024AF5-C229-4440-87B7-AC80B68DC407](https://user-images.githubusercontent.com/3709715/56453154-ece38780-633d-11e9-84ff-5e78bcca0e0f.jpeg)
The text just above could be changed to something a bit less experimental like: “__The current release of Asciidoc for Python 3 which passes it’s tests and is ready to use in your projects.__”

**Comment by elextr** [comment]
I would just make it "Traditional Asciidoc (but using Python 3)", so far we have had no complaints since Fedora swapped to this back in June 2018 although not sure how much usage there is, Fedora itself uses Asciidoctor so it might not be much.  

And maybe then the Debian packages will update since its getting close to Python 2 EOL.
