### ISSUE TITLE
The epub zen garden link is broken

### ISSUE THREAD

**Issue by jrwren** [asciidoc/asciidoc-py3#66]
On the page http://asciidoc.org/publishing-ebooks-with-asciidoc.html Under "Styling your books" there is a link to http://epubzengarden.com/ That website no longer exists at that location.

**Comment by elextr** [comment]
Transferred from `asciidoc/asciidoc` since this probably needs to be fixed when the asciidoc-py3 website is created.

**Comment by MasterOdin** [comment]
Is it even possible to do any of the steps in this section anymore given that it looks like all of the `adventures-of-sherlock-holmes` links point to 404 links. Same with the section above, but it that one at least doesn't reference anything beyond the source text which one can download from Gutenberg.

**Comment by elextr** [comment]
I don't know anything about epubzengarden.com or where it may have gone to, google finds a couple of derivatives on github, but I don't know if they do the same thing.  So yeah that part probably comes out.

The links to files on asciidoc.org that 404 still exist in the original `methods.co.nz/asciidoc/` location, but its not clear what the license for any files (the formatted versions) are, so just copying it might not be a good thing.  IIRC my past attempt to contact Stuart to clarify the license wasn't answered.  If you can see a license that I missed then we can use stuff in accordance with it to re-create the website if its considered worthwhile.

Otherwise the examples parts of the site may have to be removed.

**Comment by MasterOdin** [comment]
In looking into this, I think you could probably list the file licenses as follows:

* adventures-of-sherlock-holmes.txt -> From Project Gutenberg with the book being in the public domain
* adventures-of-sherlock-holmes.jpg -> The front image cover, probably from Project Gutenberg at time the zip was generated, but I cannot find the image anymore, and should probably update to one definitely in the public domain
* adventures-of-sherlock-holmes-docinfo.xml -> No idea, but given how minimal, I could see Stuart having made it
* adventures-of-sherlock-holmes.css -> Based on stylesheet from ePub Zen Garden, which is gone and no idea who you could contact about this. There is a [GitHub Repo](https://github.com/caraya/epub-zen) which did not capture any author information. However, best I can tell is that this site was created by the people who did [CSS Zen Garden](http://csszengarden.com/) and they use the [CreativeCommons BY-NC-SA 1.0](https://creativecommons.org/licenses/by-nc-sa/1.0/) which is pretty permissible, assuming you could find the original author. Given the above license, and the fact that it's realistically probably impossible to track this down, you're probably fine just using the file with maybe a slight notice in the file from where it's from and maybe a `If you're the author of this file, let us know so we can give proper attribution`. 
* underline.jpg -> image from the above CSS file and so probably under a similar thing, though just to be safe, might be best to replace as CSS Zen Garden does not offer a license for any images on the site.
